### ISSUE TITLE
Ошибка при вызове метода charge

### ISSUE THREAD

**Issue by temirovgroup** [paveldanilin/php-tinkoff-payment#10]
Здравствуйте!

Получаю ошибку при вызове метода charge (вызывал и так и так)
```
$charge = new Charge();
$charge->setPaymentId(10063);
$charge->setRebillId(1234);
$result = $paymentClient->charge($charge);

if ($result->isSuccess()) {
    // Успех
} else {
    // Ошибка
} 
```
и так
```
$charge = new Charge();
$charge->setTerminalKey('155525273208DEMO');
$charge->setPaymentId('2878431439');
$charge->setRebillId('1655752240416');
$charge->setToken('b580a209b486e22a8590465103dfe01538d3c12439078ebfd9027fdd2f15971c');

$result = $paymentClient->charge($charge);
```

В ответ получаю разные ошибки (при F5)
`Pada\Tinkoff\Payment\Model\Charge\ChargeResult Object
(
    [success:Pada\Tinkoff\Payment\Model\AbstractResult:private] => 
    [errorCode:Pada\Tinkoff\Payment\Model\AbstractResult:private] => 9999
    [message:Pada\Tinkoff\Payment\Model\AbstractResult:private] => Неверные параметры.
    [details:Pada\Tinkoff\Payment\Model\AbstractResult:private] => Поле TerminalKey не должно быть пустым.
    [terminalKey:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [amount:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 0
    [orderId:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [status:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [paymentId:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 0
)
`
или
`Pada\Tinkoff\Payment\Model\Charge\ChargeResult Object
(
    [success:Pada\Tinkoff\Payment\Model\AbstractResult:private] => 
    [errorCode:Pada\Tinkoff\Payment\Model\AbstractResult:private] => 201
    [message:Pada\Tinkoff\Payment\Model\AbstractResult:private] => Неверные параметры.
    [details:Pada\Tinkoff\Payment\Model\AbstractResult:private] => Поле PaymentId не должно быть пустым.
    [terminalKey:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [amount:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 0
    [orderId:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [status:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 
    [paymentId:Pada\Tinkoff\Payment\Model\Charge\ChargeResult:private] => 0
)
`

То есть жалуется то на одно, то на другое. Будто рандомно выдает ошибку по этим полям. Это может быть из-за того, что касса тестовая и карта тоже? (то есть я на этапе тестов)

**Comment by temirovgroup** [comment]
Проблема была в том, что у тестового терминала был отключен прием рекуррентных платежей. Включается через тех. поддержку. Метод charge данного расширения - не работает.

**Comment by paveldanilin** [comment]
@temirovgroup добрый день!
У вас получилось победить ошибку?

**Comment by temirovgroup** [comment]
@paveldanilin Здравствуйте! Нет, я не ковырял расширение если честно. Взял PHP класс от тинькофф и допилил под себя)

**Comment by paveldanilin** [comment]
Нужна проверка.

**Comment by paveldanilin** [comment]
Добавил пример с charge. Ошибок не обнаружено.
