### ISSUE TITLE
Совместимость с Symfony ^6.4|^7.0

### ISSUE THREAD

**Issue by Kezino** [paveldanilin/php-tinkoff-payment#11]
Павел, спасибо за прекрасный пакет! 

Шикарный код, всё по уму! 
Можно ли обновить Rest Client, чтобы была совместимость этой библиотеки с новыми версиями пакетов Symfony?

Заранее благодарю!

**Comment by paveldanilin** [comment]
Привет, спасибо за отзыв.
Да, попробую.

**Comment by paveldanilin** [comment]
@Kezino,
привет.

Добавил поддержку symfony 6.4 в версии 2.0.0 .
Есть возможность проверить?
