### ISSUE TITLE
redirectDueDate

### ISSUE THREAD

**Issue by 995533** [paveldanilin/php-tinkoff-payment#12]
Добрый день!
Спасибо за труды! 
Подскажите как мне создать платеж с redirectDueDate
Спасибо!

**Comment by paveldanilin** [comment]
@995533,
привет!

Два варианта
1. Если руками создаем объект платежа 
`$payment = new NewPayment();
$payment->setRedirectDueDate(new DateTime('now'));
`

2. Через билдер
`$payment = newPayment()
->orderId('1234')
->oneStep()
->redirectDueDate(new DateTime('now'))
`

**Comment by 995533** [comment]
> @995533, привет!
> 
> Два варианта
> 
> 1. Если руками создаем объект платежа
>    `$payment = new NewPayment(); $payment->setRedirectDueDate(new DateTime('now')); `
> 2. Через билдер
>    `$payment = newPayment() ->orderId('1234') ->oneStep() ->redirectDueDate(new DateTime('now')) `

Спасибо! все получилось!
Еще раз спасибо за труды!
