### ISSUE TITLE
SetterTrait пытается выполнить функцию

### ISSUE THREAD

**Issue by yenyasinn** [paveldanilin/php-tinkoff-payment#15]
Контекст: данный модуль используется вместе с Drupal в котором определена функция t(). 

Если используется двухфакторная оплата, то функция Pada\Tinkoff\Payment\Model\Init\PaymentBuilder::twoStep() устанавливает в объект переменную $this->payType класса PaymentBuilder значение "T". Затем Pada\Tinkoff\Payment\Normalizer\SetterTrait::setIfNotNull() пытается выполнить функцию T(), т.к. находит ее в Drupal.

**Comment by yenyasinn** [comment]
@paveldanilin посмотрите пожалуйста предоставленный pull request. Как я смотрю везде в SetterTrait::setIfNotNull передаются анонимные функции. Может проверять что используется анонимная функция?

**Comment by paveldanilin** [comment]
Для существуещего сценария использования подходит. 
Тесты прошли, влил.
Спасибо за mr :)

**Comment by paveldanilin** [comment]
@yenyasinn получится проверить с Drupal?

**Comment by yenyasinn** [comment]
@paveldanilin, спасибо, все работает теперь!
